const { Router } = require('express')
const { renderP1Describir, renderP2Describir, renderP3Accerder, renderP4SubirArchivo, renderP5Revisar, renderP7Licencia, postArchivo, getArchivo, getDocsCompletos, getDocsUser } = require('../controllers/index_controladores')
const isAuth = require('../middlewares/isAuth')
const router = Router()
router.get('/describir-documento', renderP1Describir)
router.get('/describir-documento-p2', renderP2Describir)
router.get('/acceder', renderP3Accerder)
router.get('/agregar-archivo', renderP4SubirArchivo)
router.get('/revisar', renderP5Revisar)
router.get('/licencia', renderP7Licencia)
router.post('/post-archivo', postArchivo)
router.get('/', getArchivo)
router.get('/all', getDocsCompletos)
router.get('/alll', getDocsUser)
module.exports = router
